import { chain, map, pipe, filter, whereEq, values, sortBy, prop, pluck, indexBy } from 'ramda';
import { compact } from 'ramda-adjunct';
import { componentInfo } from './components';
import { frameworks, frameworkInfo } from './frameworks';
import { writeFile } from 'fs';
import { lines, comment, h1, h2, h3, link, p, table } from './markdownUtils';
import { removeProtocol, getRepoInfo, noValue } from './utils';
import { Component, Framework } from './entities';

const disclaimer = comment('THIS FILE IS AUTOGENERATED!!! PLEASE SEE `generate-readme.ts` and the files in the `frameworks` directory if you would like to make changes');
const website = link({ text: 'react-ui-roundup.dimitrimitropoulos.com', href: 'http://react-ui-roundup.dimitrimitropoulos.com' });

const disclaimerLines = (input: any[]) => lines([disclaimer, ...input]);

const headerMarkdown = disclaimerLines([
  h1('React UI Roundup'),
  p('Are you a frontend developer or designer?  Do you wish you had a one-stop-shop you could go to see the various implementations of common components?  If so - React UI Roundup is for you!'),
  p(`An even more better version of this exact document is available at ${website}.  It has special "Open All" buttons that allow you to open every link in a table with one click!`)
])

const frameworksSectionMarkdown = (repoInfo: any) => disclaimerLines([
  h3('Framework Stats'),
  table({
    headers: [
      'Name',
      'Homepage',
      'Repository',
      'Stars',
      'Forks',
      'Issues',
      'License',
    ],
    rows: map(({ frameworkName, frameworkHomepage, repoURL }) => [
      frameworkName,
      link({ text: removeProtocol(frameworkHomepage), href: frameworkHomepage }),
      link({ text: removeProtocol(repoURL).replace(/github\.com\//, ''), href: repoURL }),
      repoInfo[repoURL]?.stargazers_count?.toLocaleString() ?? noValue,
      repoInfo[repoURL]?.forks_count?.toLocaleString() ?? noValue,
      repoInfo[repoURL]?.open_issues_count?.toLocaleString() ?? noValue,
      repoInfo[repoURL]?.license?.name?.toLocaleString() ?? noValue,
    ], frameworks),
  }),
]);

const frameworkFeaturesSectionMarkdown = disclaimerLines([
  h3('Framework Features'),
  table({
    headers: [
      'Name',
      ...pluck('name', frameworkInfo),
    ],
    rows: map(({ frameworkName, frameworkFeaturesById }) => [
      frameworkName,
      ...map(({ toMarkdown, featureId }) => (
        // @ts-ignore @ROBBBBBBBBBBBBBBB
        toMarkdown(frameworkFeaturesById[featureId])
      ), frameworkInfo),
    ], frameworks),
  })
])

const frameworksMarkdown = (repoInfo: any) => disclaimerLines([
  h2('Frameworks'),
  frameworksSectionMarkdown(repoInfo),
  frameworkFeaturesSectionMarkdown,
]);

const componentsMarkdown = disclaimerLines([
  h2('Components'),
  ...chain(({ componentId, cannonicalName, optionsById }) => {
    const optionsArray = pipe(
      values,
      sortBy(prop('name')),
    )(optionsById);

    const headers = [
      'Framework',
      'Name',
      ...pluck('name', optionsArray),
    ];

    const rows = pipe(
      chain<Framework, Component & Pick<Framework, 'frameworkName'>>(({ components, frameworkName }) => (
        map(component => ({ ...component, frameworkName }), components)
      )),
      filter(whereEq({ componentId })),
      map(({ componentName, frameworkName, componentURL, options }) => [
        frameworkName,
        link({ text: componentName, href: componentURL }),
        // @ts-ignore @ROBBBBBBBBBBBBBBB
        ...map(({ optionId, toMarkdown }) => toMarkdown(options[optionId]), optionsArray),
      ]),
    )(frameworks);

    return [
      disclaimer,
      h3(cannonicalName),
      table({
        headers,
        rows,
      }),
    ];
  }, componentInfo),
]);

const fetchAll = async () => {
  const repoInfo = await Promise.all(
    map(({ repoURL }) => getRepoInfo(repoURL), frameworks)
  );

  const readme = lines([
    headerMarkdown,
    frameworksMarkdown(indexBy(prop('html_url'), compact(repoInfo))),
    componentsMarkdown,
  ]);

  writeFile('README.md', readme, error => {
    if (error) {
      return console.error(error);
    }
  });
};

fetchAll();
